<left>
    <img src="https://kpi.ua/files/images/kpi.png" width="300" alt="kpi logo"  />
</left>

# Метод спряженого градієнта Флетчера-Рівса

ПОСТАНОВКА ЗАДАЧІ

---



**Дослідити збіжність метода Флетчера-Рівса при мінімізації кореневої функції  в залежності від**:
1. Значення точності (е).
2. Схеми обчислення похідних.
3. Виду методу одновимірного пошуку 
4. Вигляду критерію закінчення.


## Materials and Methods 

How did I solve the problem? What method I used and why? What datasets? etc.

---


**Метод сопряжённых градиентов (Метод Флетчера-Ривcа)** — метод нахождения локального экстремума функции на основе информации о её значениях и её градиенте. В случае квадратичной функции в  ${\displaystyle \mathbb {R} ^{n}}$ минимум находится не более чем за n шагов.

## Теорія

Стратегія пошуку.

Визначення. Два n-мірних вектора х і у називають сполученими по відношенню до матриці H (або H-сполученими), якщо скалярний добуток (x, Ну) = 0. Тут Н - симетрична позитивно певна матриця розміром n*n.
Стратегія методу Флетчера-Ривса полягає в побудові послідовності точок, k = 0, 1, 2, ... таких, що, k = 0, 1, 2, ...

Точки послідовності ${x^k}$ обчислюються за правилом:

$x_k = x_{k-1}+a*p_k$  

$p_k= - g_k + b_{k-1}*g_{k-1}$

$p_0= - g_k $

($b_k = \frac{‖\triangledown f(x^k)‖^2}{‖\triangledown f(x^{k-1})‖^2}$)

Величина кроку вибирається з умови мінімуму функції в напрямку руху, т. Е. В результаті рішення задачі одновимірної мінімізації: $a = argmin_\lambda f(x+\lambda*g)$

Відзначимо, що при цьому виборі $b_{k-1}$ в разі квадратичної функції f (x) = (х, Нх) + (b, х) + а напрямки $p_k,p_{k-1}$ будуть H-спряжені, тобто

($p_k,H*p_{k-1}$) = 0

При цьому в точках послідовності {$x^k$}** градієнти функції** f (x) взаємно перпендикулярні, тобто  ($\triangledown f(x^{k+1}),\triangledown f(x^k)$) = 0



*Метод Флетчера-Ривса* 

1.   [WIKI](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D1%81%D0%BE%D0%BF%D1%80%D1%8F%D0%B6%D1%91%D0%BD%D0%BD%D1%8B%D1%85_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BE%D0%B2)
2.   [machinelearning.ru](http://www.machinelearning.ru/wiki/index.php?title=%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D1%81%D0%BE%D0%BF%D1%80%D1%8F%D0%B6%D1%91%D0%BD%D0%BD%D1%8B%D1%85_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BE%D0%B2)

## Algoritm


Вхідні параметри: x- початкова точка, f(x) - функція , е - точність

1.   знайти  $\triangledown f(x)$
2.   вирахувати $a = argmin_\lambda f(x+\lambda*g)$ 
3.  $x_k = x_{k-1}+a*p_k$  
4.  $g_x =\triangledown f(x) , b_k=g^T_x*g_x/g^T_y*g_y $
5.  $p_k= - g_k + b_k*g_{k-1}$    (направлення спуску)
6.  перевірка критерія закінчення ($\frac{‖x_{k+1}-x{k}‖}{‖x{k}‖}$) 



### Теоретичне пояснення методу

${\vec{S_0}=-\nabla f(\vec{x_0})\qquad (1)}$

$\vec{x_1}=\vec{x_0}+\lambda_1 \vec{S_0} \qquad$

$\vec{S_1}=-\nabla f(\vec{x_1})+\omega_1 \vec{S_0}\ \qquad (2)$

так, чтобы оно было сопряжено с $\vec{S_0}:$

$:\vec{S_0}^T H \vec{S_1}=0 \qquad (3)$

Разложим $\nabla f(\vec{x}) в окрестности \vec{x_0}$ и подставим $\vec{x}=\vec{x_1}$:

:$\nabla f(\vec{x_1})-\nabla f(\vec{x_0})=H \, (\vec{x_1}-\vec{x_0})=\lambda_1 H \vec{S_0}$

Транспонируем полученное выражение и домножаем на $H^{-1}$ справа:

$(\nabla f(\vec{x_1})-\nabla f(\vec{x_0}))^T H^{-1}=\lambda_1 \vec{S_0}^T H^T H^{-1}$



$\vec{S_0}^T=\frac{(\nabla f(\vec{x_1})-\nabla f(\vec{x_0}))^T H^{-1}}{\lambda_1}$

Подставим полученное выражение в (3):

$\frac{(\nabla f(\vec{x_1})-\nabla f(\vec{x_0}))^T H^{-1}H\vec{S_1}}{\lambda_1}=0$

Тогда, воспользовавшись (1) и (2):

$(\nabla f(\vec{x_1})-\nabla f(\vec{x_0}))^T (-\nabla f(\vec{x_1})-\omega_1\nabla f(\vec{x_0})))=0\qquad (4)$

Если $\lambda=\arg\min_\lambda f(\vec{x_0}+\lambda \vec{S_0})$, то градиент в точке $\vec{x_1}=\vec{x_0}+\lambda \vec{S_0}$ перпендикулярен градиенту в точке $\vec{x_0}$, тогда по правилам скалярного произведения векторов:

$(\nabla f(\vec{x_0}),\nabla f(\vec{x_1}))=0$

Приняв во внимание последнее, получим из выражения (4) окончательную формулу для вычисления $\omega$

$\omega_1=\frac{||\nabla f(\vec{x_1})||^2}{||\nabla f(\vec{x_0})||^2}$

=== К-я итерация ===
На k-й итерации имеем набор $\vec{S_0},\ldots,\vec{S_{k-1}}$.

Тогда следующее направление вычисляется по формуле:

:$\vec{S_k}=-\nabla f(\vec{x_k}) - \|\nabla f(\vec{x_k})\|^2 {\cdot} \left( \frac{\nabla f(\vec{x}_{k-1})}{\|\nabla f(\vec{x}_{k-1})\|^2} + \ldots + \frac{\nabla f(\vec{x_0})}{\|\nabla f(\vec{x}_0)\|^2} \right)$

Это выражение может быть переписано в более удобном итеративном виде:

$\vec{S_k}=-\nabla f(\vec{x_k})+\omega_k \vec{S}_{k-1},\qquad \omega_i=\frac{\|\nabla f(\vec{x_i})\|^2}{\|\nabla f(\vec{x}_{i-1})\|^2},$

где $\omega_k$ непосредственно рассчитывается на k-й итерации.

----

## Function(s) defenition

### **1)**   Значення точності (е)


                 f(xk[i] + epsilon[i]) - f(xk[i])
       f'[i] =   --------------------------------- =  grad = optimize.approx_fprime(xk,f,e)
                     epsilon[i]


                    

Тест

In [14]:

import math
import importlib
import scipy
from scipy.optimize import minimize
import sys
import numpy as np
from scipy import optimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
Path = []

def FR(x0, h, e, f):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2 Градиент 
    prevgrad = 1
    pk = -1*grad
    while (any([abs(grad[i]) > e for i in range(n)])): # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), bounds=(0,)).x)  #Минимизация скалярной функции одной переменной.
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        k=k+1 #step8
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    print('Iter: ',k)
    return xcur #step10

def f6(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2
def f1(x):
  x,y = x
  return (1-x)**2 + 100*(y-x**2)**2
def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8



funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = [0.1,0.01,0.001]                                  # точность  e
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])

for j in precision :
  print('\nТОЧНІСТЬ e = ',j)
  test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],j, funcsToTest[i]))


ТОЧНІСТЬ e =  0.1
-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  57
Точки: [0.8860545  0.78454753]
Получено: 0.013013283936849324
Должно быть:  0.0
Разница:  0.013013283936849324

TEST  2
Iter:  6
Точки: [3.00012144 2.0012453 ]
Получено: 2.9949296373135842e-05
Должно быть:  0.0
Разница:  2.9949296373135842e-05

TEST  3
Iter:  19
Точки: [0.96978591 0.94045852 1.02955557 1.0601202 ]
Получено: 0.003223385825443792
Должно быть:  0.0
Разница:  0.003223385825443792

TEST  4
Iter:  20
Точки: [ 0.18759546 -0.0188941   0.07301611  0.07472258]
Получено: 0.0023793973083710432
Должно быть:  0.0
Разница:  0.0023793973083710432

TEST  5
Iter:  1
Точки: [9.4950936e-11 9.4950936e-11]
Получено: 0.0
Должно быть:  0.0
Разница:  0.0

TEST  6
Iter:  2
Точки: [4.99982627 5.99994568]
Получено: 1.2368158649809798e-07
Должно быть:  0.0
Разница:  1.2368158649809798e-07

ТОЧНІСТЬ e =  0.01
-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  

Висновок: При збільшені точності розрахункці збільшується кількість ітерацій методу. Але це збільшення виражається на складних функціяї більшої розмірності. Серед  ${\displaystyle \mathbb {R} ^{2}}$ збільшення ітерація в проміжку +- 2

### 2) Схеми обчислення похідних. 

F'(x0) = (${f(x+h)}$-$f(x)$) / h  (Forward difference)

F'(x0) = (${f(x)}$-$f(x+h)$) / h (Backward difference)

F'(x0) = $(f(x+h)-f(x-h)) / 2h$ (Central difference)

In [15]:
pip install numdifftools

In [16]:
import numdifftools as nd

In [17]:

import math
import importlib
import scipy
from scipy.optimize import minimize
import sys
import numpy as np
from scipy import optimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
Path = []

def FR(x0, h, e, f,m):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = nd.Gradient(f,method=m, step = 0.001)(xcur) # step2 Градиент Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while (any([abs(grad[i]) > e for i in range(n)])): # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), bounds=(0,)).x)  #Минимизация скалярной функции одной переменной.
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        
        k=k+1 #step8
        prevgrad=grad
        grad=nd.Gradient(f,method=m, step = 0.001)(xcur) #step2
    print('Iter: ',k)
    return xcur #step10

def f1(x):
  x,y = x
  return (1-x)**2 + 100*(y-x**2)**2
def f6(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2

def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8



funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.01                                  # точность  e
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])

m = ['central','forward','backward']
for j in m:
  print('метод:',j)
  test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i],j))

метод: central
-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  17
Точки: [0.98916962 0.97841327]
Получено: 0.00011748427314399327
Должно быть:  0.0
Разница:  0.00011748427314399327

TEST  2
Iter:  8
Точки: [2.99999989 1.99999985]
Получено: 1.175245358309787e-12
Должно быть:  0.0
Разница:  1.175245358309787e-12

TEST  3
Iter:  21
Точки: [0.99900645 0.99801255 1.00094249 1.0018922 ]
Получено: 3.47510972426318e-06
Должно быть:  0.0
Разница:  3.47510972426318e-06

TEST  4
Iter:  34
Точки: [ 0.08843603 -0.00881742  0.04923667  0.05009872]
Получено: 0.00015789604137137912
Должно быть:  0.0
Разница:  0.00015789604137137912

TEST  5
Iter:  1
Точки: [9.46599465e-11 9.46599465e-11]
Получено: 0.0
Должно быть:  0.0
Разница:  0.0

TEST  6
Iter:  2
Точки: [5. 6.]
Получено: 3.8058594372387715e-24
Должно быть:  0.0
Разница:  3.8058594372387715e-24
метод: forward
-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  25
Точки: [0.988127

Висновок: серед трьох варіантів знаходження похідних а сапе

### 3)Методи одновимірного пошуку . 

Type of solver.

‘Golden’ золотое сечение 

In [18]:

import math
import importlib
import scipy
from scipy.optimize import minimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
import sys
import numpy as np
from scipy import optimize

Path = []

def FR(x0, h, e, f,j):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2  Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while (any([abs(grad[i]) > e**2 for i in range(n)])): # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), method = j, bounds=(-5,5)).x)  #Минимизация скалярной функции одной переменной.
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        k=k+1 #step8
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    print('Iter: ',k)
    return xcur #step10

def f1(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2

def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8

def f6(x):
    x, y = x
    return (-0.15*y)**2 + (0.08*x)**2 - 4*math.cos(-1.2*y) - 4*math.cos(0.64*x) + 8




funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.01                                  # точность
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])
        # self.assertAlmostEqual(func_res[i], funcsToTest[i](res), delta=eps)
m = ['Golden','Bounded']
for j in m :
  print('\nметод  = ',j)
  test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i],j))


метод  =  Golden
-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  2
Точки: [5.00000023 6.00000005]
Получено: 2.190311689494782e-13
Должно быть:  0.0
Разница:  2.190311689494782e-13

TEST  2
Iter:  8
Точки: [3.00000011 2.00000015]
Получено: 1.1467758440011344e-12
Должно быть:  0.0
Разница:  1.1467758440011344e-12

TEST  3
Iter:  37
Точки: [0.99996823 0.99993633 1.00003259 1.00006526]
Получено: 3.761240861118973e-09
Должно быть:  0.0
Разница:  3.761240861118973e-09

TEST  4
Iter:  58
Точки: [ 0.01849968 -0.00184981  0.00975219  0.00975784]
Получено: 2.6649935606528777e-07
Должно быть:  0.0
Разница:  2.6649935606528777e-07

TEST  5
Iter:  1
Точки: [-9.64898605e-09 -9.64898605e-09]
Получено: 0.0
Должно быть:  0.0
Разница:  0.0

TEST  6
Iter:  4
Точки: [ 1.64430983e-08 -3.77462160e-08]
Получено: 3.552713678800501e-15
Должно быть:  0.0
Разница:  3.552713678800501e-15

метод  =  Bounded
-----------------------
test_fletcher_reeves
-----------------------



In [19]:

import math
import importlib
import scipy
from scipy.optimize import minimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
import sys
import numpy as np
from scipy import optimize

Path = []

def FR(x0, h, e, f):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2  Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while (any([abs(grad[i]) > e**2 for i in range(n)])): # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), method = j, bounds=(0,3)).x)  #Минимизация скалярной функции одной переменной.
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        k=k+1 #step8
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    print('Iter: ',k)
    return xcur #step10

def f1(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2

def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8

def f6(x):
    x, y = x
    return (-0.15*y)**2 + (0.08*x)**2 - 4*math.cos(-1.2*y) - 4*math.cos(0.64*x) + 8





funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.01                                  # точность
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])
        # self.assertAlmostEqual(func_res[i], funcsToTest[i](res), delta=eps)

test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i]))

-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  2
Точки: [5.0000003  6.00000009]
Получено: 3.7339767896569356e-13
Должно быть:  0.0
Разница:  3.7339767896569356e-13

TEST  2
Iter:  8
Точки: [3.00000011 2.00000015]
Получено: 1.205000423996479e-12
Должно быть:  0.0
Разница:  1.205000423996479e-12

TEST  3
Iter:  94
Точки: [-1.46300044e+18  5.11522357e+15 -1.61910145e+19  2.46150758e+16]
Получено: 6.18544463968857e+78
Должно быть:  0.0
Разница:  6.18544463968857e+78

TEST  4
Iter:  58
Точки: [ 0.01629782 -0.00162987  0.0041233   0.00412328]
Получено: 2.292055764495631e-07
Должно быть:  0.0
Разница:  2.292055764495631e-07

TEST  5
Iter:  1
Точки: [1.21896259e-07 1.21896259e-07]
Получено: 4.085620730620576e-14
Должно быть:  0.0
Разница:  4.085620730620576e-14

TEST  6
Iter:  6
Точки: [-5.33455591e-09 -5.19538274e+00]
Получено: 0.6120675513133689
Должно быть:  0.0
Разница:  0.6120675513133689


### 4)Критерію закінчення.


1.  grad < e
2.   ${‖x_{k+1}-x_{k}‖/‖x_{k}‖}<e$ 
3.    $|f(x_k+1)-f(x_k)| <e$
4.   $ ‖Sk‖≤ε$



In [20]:
import unittest
import math
import importlib
import scipy
from scipy.optimize import minimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
import sys
import numpy as np
from scipy import optimize

Path = []

def FR(x0, h, e, f):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2  Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while (any([abs(grad[i]) > e for i in range(n)])): # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), bounds=(0,)).x)  #Минимизация скалярной функции одной переменной.
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        k=k+1 #step8
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    print('Iter: ',k)
    return xcur #step10


def f1(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2

def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8
'''
def f6(x):
    x, y = x
    return (-0.15*y)**2 + (0.08*x)**2 - 4*math.cos(-1.2*y) - 4*math.cos(0.64*x) + 8
'''

def f6(x):
  x,y = x
  return (1-x)**2 + 100*(y-x**2)**2




funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.001                                  # точность
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])
        # self.assertAlmostEqual(func_res[i], funcsToTest[i](res), delta=eps)

test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i]))

-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  3
Точки: [4.9999934  6.00035431]
Получено: 1.2571107209964342e-07
Должно быть:  0.0
Разница:  1.2571107209964342e-07

TEST  2
Iter:  8
Точки: [3.00000022 2.0000003 ]
Получено: 4.688936135306726e-12
Должно быть:  0.0
Разница:  4.688936135306726e-12

TEST  3
Iter:  22
Точки: [0.99986567 0.99973015 1.00014777 1.00029534]
Получено: 7.847454550120894e-08
Должно быть:  0.0
Разница:  7.847454550120894e-08

TEST  4
Iter:  45
Точки: [ 0.03980054 -0.00398146  0.01240518  0.01243752]
Получено: 6.2986518830998165e-06
Должно быть:  0.0
Разница:  6.2986518830998165e-06

TEST  5
Iter:  1
Точки: [9.39196498e-11 9.39196498e-11]
Получено: 0.0
Должно быть:  0.0
Разница:  0.0

TEST  6
Iter:  0
Точки: [1. 1.]
Получено: 0.0
Должно быть:  0.0
Разница:  0.0


 $|f(x_k+1)-f(x_k)| <e$

In [21]:
import unittest
import math
import importlib
import scipy
from scipy.optimize import minimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
import sys
import numpy as np
from scipy import optimize

Path = []

def FR(x0, h, e, f):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2  Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while True: # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), bounds=(0,)).x)  #Минимизация скалярной функции одной переменной.
        if abs(f(xcur + a*pk)-f(xcur)) < e:
          break
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        k=k+1 #step8
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    print('Iter: ',k)
    return xcur #step10

    
def f1(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2

def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8

def f6(x):
    x, y = x
    return (-0.15*y)**2 + (0.08*x)**2 - 4*math.cos(-1.2*y) - 4*math.cos(0.64*x) + 8

def f7(x):
    x, y = x
    return -10/(0.005*(x**2+y**2)-math.cos(x)*math.cos(y/1.41421356237309504880168)+2)+10




funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.001                                  # точность
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])
        # self.assertAlmostEqual(func_res[i], funcsToTest[i](res), delta=eps)

test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i]))

-----------------------
test_fletcher_reeves
-----------------------

TEST  1
Iter:  2
Точки: [5.0015862  6.00047307]
Получено: 1.0287884526650646e-05
Должно быть:  0.0
Разница:  1.0287884526650646e-05

TEST  2
Iter:  6
Точки: [3.00012939 2.00129509]
Получено: 3.250232574228901e-05
Должно быть:  0.0
Разница:  3.250232574228901e-05

TEST  3
Iter:  11
Точки: [0.90648487 0.82112707 1.08569973 1.17900701]
Получено: 0.02893828374432794
Должно быть:  0.0
Разница:  0.02893828374432794

TEST  4
Iter:  16
Точки: [ 0.21487124 -0.02067734  0.12548575  0.12819374]
Получено: 0.006112112014209558
Должно быть:  0.0
Разница:  0.006112112014209558

TEST  5
Iter:  1
Точки: [9.39196498e-11 9.39196498e-11]
Получено: 0.0
Должно быть:  0.0
Разница:  0.0

TEST  6
Iter:  2
Точки: [0.00255145 0.00686865]
Получено: 0.00014230881173205034
Должно быть:  0.0
Разница:  0.00014230881173205034


${‖x_{k+1}-x_{k}‖/‖x_{k}‖}<e$ 

In [22]:
import unittest
import math
import importlib
import scipy
from scipy.optimize import minimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
import sys
import numpy as np
from scipy import optimize

Path = []

def FR(x0, h, e, f):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2  Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while True: # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), bounds=(0,)).x)  #Минимизация скалярной функции одной переменной.
        if ((np.linalg.norm(xcur + a*pk-xcur)/(np.linalg.norm(xcur)) < e)):
          print('різниця:',f(xcur + a*pk)-f(xcur))
          break
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        k=k+1 #step8
        
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    print('ітерація',k)
    return xcur #step10

    
def f1(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2

def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8

def f6(x):
    x, y = x
    return (-0.15*y)**2 + (0.08*x)**2 - 4*math.cos(-1.2*y) - 4*math.cos(0.64*x) + 8





funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.1                                  # точность
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])
        # self.assertAlmostEqual(func_res[i], funcsToTest[i](res), delta=eps)

test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i]))

-----------------------
test_fletcher_reeves
-----------------------

TEST  1
різниця: -1.2410504475805416e-07
ітерація 2
Точки: [4.99982393 5.99994715]
Получено: 1.267939239172541e-07
Должно быть:  0.0
Разница:  1.267939239172541e-07

TEST  2
різниця: -0.10710341295425091
ітерація 4
Точки: [3.0240658  1.90082281]
Получено: 0.13372614086998266
Должно быть:  0.0
Разница:  0.13372614086998266

TEST  3
різниця: -5.313229970704231
ітерація 8
Точки: [0.86978398 0.5733929  1.02896951 0.94205666]
Получено: 6.9591380459166015
Должно быть:  0.0
Разница:  6.9591380459166015

TEST  4
різниця: -0.11348540688476716
ітерація 4
Точки: [ 0.84036629 -0.05664325  0.33192523  0.44314399]
Получено: 0.655327014069402
Должно быть:  0.0
Разница:  0.655327014069402

TEST  5
різниця: 0.0
ітерація 3
Точки: [6.73550719e-13 6.73550719e-13]
Получено: 0.0
Должно быть:  0.0
Разница:  0.0

TEST  6
різниця: 0.0
ітерація 7
Точки: [ 2.46998347e-06 -2.11378548e-07]
Получено: 5.1665338673956285e-12
Должно быть:  0.0
Разни

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: RuntimeWarning: divide by zero encountered in double_scalars


$ ‖Sk‖≤ε$

In [23]:

import math
import importlib
import scipy
from scipy.optimize import minimize
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
import sys
import numpy as np
from scipy import optimize

Path = []

def FR(x0, h, e, f):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2  Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while (any([abs(pk[i]) > e**2 for i in range(n)])): # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), bounds=(0,)).x)  #Минимизация скалярной функции одной переменной.
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        k=k+1 #step8
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    
    print(Path)
    print('ітерація',k)
    return xcur #step10

    
def f1(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2

def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8

def f6(x):
  x,y = x
  return (1-x)**2 + 100*(y-x**2)**2





funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.01                                  # точность
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])
        # self.assertAlmostEqual(func_res[i], funcsToTest[i](res), delta=eps)

test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i]))

-----------------------
test_fletcher_reeves
-----------------------

TEST  1
[array([0., 0.]), array([5.33007333, 1.59902185]), array([5.00000016, 6.00000005]), array([5.        , 6.00000003])]
ітерація 3
Точки: [5.         6.00000003]
Получено: 1.22366427410725e-15
Должно быть:  0.0
Разница:  1.22366427410725e-15

TEST  2
[array([0., 0.]), array([5.33007333, 1.59902185]), array([5.00000016, 6.00000005]), array([5.        , 6.00000003]), array([0., 0.]), array([1.78269957, 2.80138513]), array([2.25988956, 2.99187121]), array([2.68681699, 1.92236778]), array([3.02409979, 1.90069828]), array([3.02914511, 1.97922814]), array([3.00012671, 2.00127367]), array([2.99961365, 2.00059834]), array([3.00000011, 2.00000015]), array([2.99999997, 2.00000006])]
ітерація 9
Точки: [2.99999997 2.00000006]
Получено: 5.3069191655870665e-14
Должно быть:  0.0
Разница:  5.3069191655870665e-14

TEST  3
[array([0., 0.]), array([5.33007333, 1.59902185]), array([5.00000016, 6.00000005]), array([5.        , 6.000

### загальний метод

In [24]:
machineAcc = 0.001
# Метод сопряженных градиентов (Флетчера-Ривса)
import sys
import numpy as np
from scipy import optimize

Path = []

def FR(x0, h, e, f):
    xcur = np.array(x0)
    Path.append(xcur)
    h = np.array(h)
    n = len(x0)
    k = 0 # step1
    grad = optimize.approx_fprime(xcur, f, e**4) # step2  Конечно-разностная аппроксимация градиента скалярной функции.
    prevgrad = 1
    pk = -1*grad
    while (any([abs(grad[i]) > e**2 for i in range(n)])): # step3 Итерации продолжаются до тех пор, пока выполняется условие
        if (k%n==0): # step4
            pk = -1*grad
        else:                                                     #Функция linalg.norm() вычисляет норму матрицы
            bk = (np.linalg.norm(grad)**2)/(np.linalg.norm(prevgrad)**2) # Коэффициенты bk выбираются так, чтобы векторы p_k и p_{k + 1} были сопряжёнными относительно А.
            prevpk = pk
            pk = -1*grad + bk*prevpk # step6
        a = (optimize.minimize_scalar(lambda x: f(xcur+pk*x), bounds=(0,)).x)  #Минимизация скалярной функции одной переменной.
        xcur = xcur + a*pk #step8
        Path.append(xcur)
        print('ітерація' ,k)
        k=k+1 #step8
        prevgrad=grad
        grad=optimize.approx_fprime(xcur, f, e**4) #step2
    return xcur #step10




## Тест

In [25]:

import math
import importlib
import scipy
from scipy.optimize import minimize

def f6(x):
    return 4*pow((x[0]-5),2) + pow((x[1]-6),2) # 4*(x1-5)^2 + (x2-6)^2
def f1(x):
  x,y = x
  return (1-x)**2 + 100*(y-x**2)**2
def f2(x):
    return pow(x[0]*x[0]+x[1]-11, 2) + pow(x[0]+x[1]*x[1]-7,2)   #(x1^2 + x2-11)^2 + (x1+x2^2-7)^2

def f3(x):
    return (100*(x[1]-x[0]**2)**2 + 
    (1-x[0])**2 + 
    90*(x[3]-x[2]**2)**2 + 
    (1-x[2])**2 + 
    10.1*((x[1]-1)**2+(x[3]-1)**2) + 
    19.8*(x[1]-1)*(x[3]-1))

def f4(x):
    x1,x2,x3,x4 = x
    return ((x1+10*x2)**2+
            5*(x3-x4)**2+
            (x2-2*x3)**4+
            10*(x1-x4)**4)

def f5(x):
    x, y = x
    return (0.1*x**2) + (0.1*y**2) - 4*math.cos(0.8*x) - 4*math.cos(0.8*y) + 8






funcsToTest = [f1, f2, f3, f4, f5, f6] 
startPoint = [[0.,0.],[0.,0.],[0.,0.,0.,0.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
step = [[1.,1.],[1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.], [1., 1.], [1., 1.]]
precision = 0.001                                  # точность
func_res = [0.,0.,0.,0.,0.,0.]
        
def test_function(method_name, test_fnc):
    print("-----------------------")
    print(method_name)
    print("-----------------------")
    eps = precision
    for i in range(len(funcsToTest)):
        print("\nTEST ", i+1 )
        res = test_fnc(i)
        print("Точки:", res)
        print("Получено:",  funcsToTest[i](res))
        print("Должно быть: ", func_res[i])
        print("Разница: ", funcsToTest[i](res) - func_res[i])
        # self.assertAlmostEqual(func_res[i], funcsToTest[i](res), delta=eps)

test_function("test_fletcher_reeves",lambda i: FR(startPoint[i],step[i],precision, funcsToTest[i]))

-----------------------
test_fletcher_reeves
-----------------------

TEST  1
ітерація 0
ітерація 1
ітерація 2
ітерація 3
ітерація 4
ітерація 5
ітерація 6
ітерація 7
ітерація 8
ітерація 9
ітерація 10
ітерація 11
ітерація 12
ітерація 13
ітерація 14
ітерація 15
ітерація 16
ітерація 17
ітерація 18
ітерація 19
ітерація 20
Точки: [0.99999972 0.99999943]
Получено: 8.039827608451909e-14
Должно быть:  0.0
Разница:  8.039827608451909e-14

TEST  2
ітерація 0
ітерація 1
ітерація 2
ітерація 3
ітерація 4
ітерація 5
ітерація 6
ітерація 7
ітерація 8
ітерація 9
Точки: [3. 2.]
Получено: 2.978162247010569e-20
Должно быть:  0.0
Разница:  2.978162247010569e-20

TEST  3
ітерація 0
ітерація 1
ітерація 2
ітерація 3
ітерація 4
ітерація 5
ітерація 6
ітерація 7
ітерація 8
ітерація 9
ітерація 10
ітерація 11
ітерація 12
ітерація 13
ітерація 14
ітерація 15
ітерація 16
ітерація 17
ітерація 18
ітерація 19
ітерація 20
ітерація 21
ітерація 22
ітерація 23
ітерація 24
ітерація 25
ітерація 26
ітерація 27
ітерація 28
ітер

In [26]:
Path[:]

[array([0., 0.]),
 array([0.16126202, 0.        ]),
 array([0.29283455, 0.05059378]),
 array([0.28247763, 0.07752688]),
 array([0.43178023, 0.16564688]),
 array([0.42451759, 0.17795255]),
 array([0.55926263, 0.29508902]),
 array([0.55232128, 0.30307344]),
 array([0.67464405, 0.44065507]),
 array([0.66882013, 0.44583307]),
 array([0.77671609, 0.59203431]),
 array([0.77223162, 0.59534376]),
 array([0.86378158, 0.73804868]),
 array([0.86061997, 0.74007683]),
 array([0.93297506, 0.86542411]),
 array([0.93103524, 0.86654389]),
 array([0.97980642, 0.95775996]),
 array([0.97893367, 0.95822661]),
 array([0.99878893, 0.99721995]),
 array([0.99864772, 0.99729186]),
 array([1.00000021, 0.99999918]),
 array([0.99999972, 0.99999943]),
 array([0., 0.]),
 array([1.78087461, 2.80161981]),
 array([2.25801968, 2.99249723]),
 array([2.68618687, 1.92165296]),
 array([3.02429   , 1.89988773]),
 array([3.02938371, 1.97905026]),
 array([3.00012939, 2.00129509]),
 array([2.99960728, 2.00060843]),
 array([3.00

## Conclusions

Метод сполучених градієнтів є методом першого порядку, в той же час швидкість його збіжності квадратична. Цим він вигідно відрізняється від звичайних градієнтних методів. Наприклад, метод найшвидшого спуску і метод координатного спуску для квадратичної функції сходяться лише в межі, в той час як метод сполучених градієнтів оптимізує квадратичную функцію за кінцеве число ітерацій.